version: "2"
services:
  # PHP
  php:
    restart: always
    build:
      context: .
      dockerfile: php-Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./www:/usr/local/nginx/html/:rw

  # NGINX
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www:/usr/local/nginx/html/:rw
      - ./logs/nginx:/tmp/:rw
    command: /bin/sh -c "nginx -g 'daemon off;'"

  #  MYSQL
  db:
    restart: always
    image: hypriot/rpi-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql:rw
      - ./www:/usr/local/nginx/html/:rw

