version: "2"
services:
  # PYTHON
  python:
    restart: always
    build: 
      context: .
      dockerfile: pip-Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./www:/usr/local/nginx/html/:rw

  # NGINX
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www:/usr/local/nginx/html/:rw
      - ./logs/nginx:/tmp/:rw
    command: /bin/sh -c "nginx -g 'daemon off;'"

